[package]
name = "drmemd"
version = "0.7.1"
authors = ["Rich Neswold <rich.neswold@gmail.com>"]
edition = "2021"
description = "Main process of the DrMem control system"
homepage = "https://github.com/DrMemCS/drmem"
repository = "https://github.com/DrMemCS/drmem"
license = "MIT"
categories = ["embedded", "hardware-support"]
keywords = ["control-system", "automation"]

[badges]
maintenance = { status = "actively-developed" }

[build-dependencies]
cfgrammar = "0.14"
lrlex = "0.14"
lrpar = "0.14"

[dependencies]
futures.workspace = true
futures.default-features = false
futures.features = ["alloc", "std"]

toml.workspace = true
toml.default-features = false
toml.features = ["parse"]

tokio.workspace = true
tokio.default-features = false
tokio.features = ["rt-multi-thread", "time", "fs", "macros"]

tokio-stream.workspace = true
tokio-stream.default-features = false
tokio-stream.features = ["net", "sync"]

tracing.workspace = true
tracing.default-features = false
tracing.features = ["attributes"]

tracing-subscriber.workspace = true
tracing-subscriber.default-features = false
tracing-subscriber.features = ["ansi"]

serde.workspace = true
serde.default-features = false
serde.features = ["derive"]

serde_json.workspace = true
serde_json.default-features = false
serde_json.features = ["std"]

clap.version = "4"
clap.default-features = false
clap.features = ["cargo", "std"]

chrono.workspace = true
chrono.default-features = false
chrono.features = ["clock"]

palette.workspace = true
palette.default-features = false
palette.features = ["libm", "named", "named_from_str"]

lazy_static = { version = "1", default-features = false }

drmem-api = { path = "../drmem-api", version = "0.7" }

cfgrammar.version = "0.14"
cfgrammar.default-features = false

lrlex.version = "0.14"
lrlex.default-features = false

lrpar.version = "0.14"
lrpar.default-features = false

[dev-dependencies]

tokio-stream.workspace = true
tokio-stream.default-features = false
tokio-stream.features = ["sync", "time"]

noop-waker = "0.1"

# This section defines the driver dependencies. Most drivers are
# optional, but a few drivers define common devices for a `drmem`
# installation.

[dependencies.drmem-drv-hue]
path = "../drivers/drmem-drv-hue"
version = "0.1"
optional = true

[dependencies.drmem-drv-ntp]
path = "../drivers/drmem-drv-ntp"
version = "0.7"
optional = true

[dependencies.drmem-drv-sump]
path = "../drivers/drmem-drv-sump"
version = "0.7"
optional = true

[dependencies.drmem-drv-tplink]
path = "../drivers/drmem-drv-tplink"
version = "0.7"
optional = true

[dependencies.drmem-drv-weather-wu]
path = "../drivers/drmem-drv-weather-wu"
version = "0.7"
optional = true

# This section defines the optional dependencies for backend storage.

[dependencies.redis]
version = "0.32"
default-features = false
features = ["tokio-comp", "streams", "tcp_nodelay"]
optional = true

# This section defines the optional dependencies for the 'graphql'
# feature.

[dependencies.async-graphql]
version = "7"
default-features = false
features = ["chrono"]
optional = true

[dependencies.async-graphql-axum]
version = "7"
default-features = false
optional = true

[dependencies.async-stream]
version = "0.3"
default-features = false
optional = true

[dependencies.axum]
version = "0.8"
default-features = false
features = ["ws"]
optional = true

[dependencies.axum-server]
version = "0.7"
default-features = false
features = ["tls-rustls-no-provider"]
optional = true

[dependencies.tower]
version = "0.5"
default-features = false
optional = true

[dependencies.tower-http]
version = "0.7"
default-features = false
features = ["compression-gzip", "cors"]
optional = true

[dependencies.libmdns]
version = "0.10"
default-features = false
optional = true

[dependencies.rustls-pki-types]
version = "1.11"
default-features = false
optional = true

[dependencies.ring]
version = "0.17"
default-features = false
optional = true

[dependencies.rustls-pemfile]
version = "1"
default-features = false
optional = true

# These are features that can be enabled for drmem.

[features]
default = []

# Backends

simple-backend = []
redis-backend = ["dep:redis", "graphql"]

# Client APIs

no-client = []
graphql = ["dep:axum", "dep:axum-server", "dep:async-graphql",
           "dep:async-graphql-axum", "dep:async-stream", "dep:tower",
           "dep:tower-http", "dep:libmdns", "dep:rustls-pki-types",
           "dep:ring", "dep:rustls-pemfile"]
graphiql = ["graphql"]

# Drivers

all-drivers = ["drmem-drv-hue", "drmem-drv-ntp", "drmem-drv-sump",
               "drmem-drv-tplink", "drmem-drv-weather-wu"]
